micronaut.application.name=sistema-aluguel
micronaut.views.folder=templates/

datasources.default.url=jdbc:sqlite:clientes.db
datasources.default.driver-class-name=org.sqlite.JDBC

jpa.default.packages-to-scan=br.com.sistemaaluguel.domain
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

micronaut.server.port=8080